### ISSUE TITLE
ライセンスがわからない

### ISSUE THREAD

**Issue by hogehiga** [o24/pi_weather#1]
こんにちは、このソフトウェアを便利に使わせてもらっています。

いくつか手を入れたい箇所があるのですが、ライセンスがわからないためそれができません。よろしければライセンスを明示していただけないでしょうか。

よろしくお願いいたします。

**Comment by o24** [comment]
失礼しました。

ライセンスはMITになります。
ライセンスファイルをアップしておきました。

コードにお見苦しい箇所が多々あると思いますが、好きなように直しちゃって下さい！

**Comment by hogehiga** [comment]
ありがとうございます :smile:
